# Generated by Django 5.1.7 on 2026-04-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssessmentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("state", models.CharField(max_length=50)),
                ("property_type", models.CharField(max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("composite_score", models.IntegerField()),
                ("flood_score", models.IntegerField()),
                ("rainfall_score", models.IntegerField()),
                ("heat_score", models.IntegerField()),
                ("coastal_score", models.IntegerField()),
                ("grade", models.CharField(max_length=1)),
                ("grade_label", models.CharField(max_length=60)),
                ("exposure_summary", models.TextField()),
                ("cost_low", models.CharField(max_length=30)),
                ("cost_high", models.CharField(max_length=30)),
                ("recommendations", models.TextField()),
                ("data_sources_used", models.JSONField(default=list)),
                ("data_retrieved_at", models.DateTimeField(auto_now_add=True)),
                ("data_notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="core_assess_latitud_25a12b_idx",
                    ),
                    models.Index(fields=["state"], name="core_assess_state_054264_idx"),
                ],
            },
        ),
    ]
